package com.moemaair.lictionary.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF616200)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE8E970)
val md_theme_light_onPrimaryContainer = Color(0xFF1C1D00)
val md_theme_light_secondary = Color(0xFF606043)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE6E4BF)
val md_theme_light_onSecondaryContainer = Color(0xFF1C1D06)
val md_theme_light_tertiary = Color(0xFF3D6657)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBFECD9)
val md_theme_light_onTertiaryContainer = Color(0xFF002117)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1C17)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1C17)
val md_theme_light_surfaceVariant = Color(0xFFE6E3D1)
val md_theme_light_onSurfaceVariant = Color(0xFF48473A)
val md_theme_light_outline = Color(0xFF797869)
val md_theme_light_inverseOnSurface = Color(0xFFF4F0E8)
val md_theme_light_inverseSurface = Color(0xFF31312B)
val md_theme_light_inversePrimary = Color(0xFFCBCC58)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF616200)
val md_theme_light_outlineVariant = Color(0xFFC9C7B6)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFCBCC58)
val md_theme_dark_onPrimary = Color(0xFF323200)
val md_theme_dark_primaryContainer = Color(0xFF494900)
val md_theme_dark_onPrimaryContainer = Color(0xFFE8E970)
val md_theme_dark_secondary = Color(0xFFCAC8A5)
val md_theme_dark_onSecondary = Color(0xFF323218)
val md_theme_dark_secondaryContainer = Color(0xFF48482D)
val md_theme_dark_onSecondaryContainer = Color(0xFFE6E4BF)
val md_theme_dark_tertiary = Color(0xFFA4D0BD)
val md_theme_dark_onTertiary = Color(0xFF0A372A)
val md_theme_dark_tertiaryContainer = Color(0xFF254E40)
val md_theme_dark_onTertiaryContainer = Color(0xFFBFECD9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1C17)
val md_theme_dark_onBackground = Color(0xFFE6E2DA)
val md_theme_dark_surface = Color(0xFF1C1C17)
val md_theme_dark_onSurface = Color(0xFFE6E2DA)
val md_theme_dark_surfaceVariant = Color(0xFF48473A)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9C7B6)
val md_theme_dark_outline = Color(0xFF939182)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1C17)
val md_theme_dark_inverseSurface = Color(0xFFE6E2DA)
val md_theme_dark_inversePrimary = Color(0xFF616200)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFCBCC58)
val md_theme_dark_outlineVariant = Color(0xFF48473A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF616200)

val NeutralColor = Color(0xFF78909C)
val HappyColor = Color(0xFFFFEE58)
val RomanticColor = Color(0xFFEC407A)
val CalmColor = Color(0xFF42A5F5)
val TenseColor = Color(0xFFFF7043)
val LonelyColor = Color(0xFF8D6E63)
val MysteriousColor = Color(0xFF26A69A)
val AngryColor = Color(0xFFEF5350)
val AwfulColor = Color(0xFF66BB6A)
val SurprisedColor = Color(0xFF29B6F6)
val DepressedColor = Color(0xFFBDBDBD)
val DisappointedColor = Color(0xFFAB47BC)
val ShamefulColor = Color(0xFF7E57C2)
val HumorousColor = Color(0xFFFFCA28)
val SuspiciousColor = Color(0xFFD4E157)
val BoredColor = Color(0xFF26C6DA)
